### ISSUE TITLE
Thoughts about adding new features?

### ISSUE THREAD

**Issue by teppolainio** [bassetassen/crmsvcutilextensions#4]
Hi Sebastian!

I found out this project of your about CrmSvcUtil extension Nuget. What kind of plans you have about future of this library? I'm asking because I like to be able to script code generation stuff into version control and that isn't so straightforward with XrmToolBox code generator.

At my previous employer I implemented quite a similar tool what you've put here into GitHub. I extended that tool quite a bit with for example with localization options for optionset labels. At my current employer we'd have needs for similar functionalities. I'm wondering if you have will to spend some time with me to make your library to have some new features. I wouldn't like to increase NuGet clutter by introducing another library for doing basically the same stuff.

I can make pull request with features but you'd still have to merge them. I'd also like to improve NuGet package installation so that it puts assembly straight into bin\coretools (as CrmSdk NuGet package puts for example CrmSvcUtil.exe).

**Comment by bassetassen** [comment]
Hi @teppolainio,
Sorry for the late reply, I did not notice the issue here in github.

I do not have any specific plans for this as it is currently doing what is need for my regular work. But if you or someone else needs some new features I am more then happy to help out with that and will also accept PRs.

**Comment by teppolainio** [comment]
Thanks @bassetassen.

No problem with late reply. I'm still in process of going through alternatives and what would be nice on long term. There seems to be few pretty nice alternatives (spkl and DLaB.Xrm.EarlyBoundGenerator) even though there are some features on both of them I'm not really happy with. Another one seems is having really long PR acceptance causing for example optionset values like "Määräpäivä" being labeled as "Unknown1" as PR isn't accepted. Other one seems to want to use translitteration on optionsets which would create "Maeaeraepaeivae" from "Määräpäivä" even though latter one is perfectly valid .NET enum value.

I'll see what we'll do. I'm going to close this now and might do some PR if other alternatives aren't suitable.
